# Generated by Django 4.0 on 2022-09-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_customuser_address_customuser_phone_customuser_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='types',
            field=models.CharField(choices=[('User', 'User'), ('Driver', 'Driver'), ('Admin', 'Admin')], max_length=10, null=True),
        ),
    ]
